---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    provider: cloudflare
    domainFilters:
      - findingway.io
    sources:
      - traefik-proxy
    rbac:
      create: true
      additionalPermissions:
      - apiGroups: ["traefik.containo.us","traefik.io"]
        resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
        verbs: ["get","watch","list"]
    env:
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare
            key: cloudflare_api_key
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare
            key: cloudflare_api_email