---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: kube-system
spec:
  type: "oci"
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: external-dns
      version: 8.7.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    provider: cloudflare
    cloudflare:
      secretName: cloudflare