apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  base: cluster

resources:
- ./sealed-secrets.yaml
- ./sealed-secret.yaml
- ./open-telemetry
- ./external-dns
- ./cert-manager
- ./vultr-ccm
