---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: kube-system
spec:
  encryptedData:
    cloudflare_api_token: AgAVVsesl/IBxjUK1tjdWXK+FeZ1wrpuUhTVROgwbyt5IzHDQaVUV7z5lHW45ektSYKu+dLbiHQeLumBbNoWLOhAaeAQlE0FkGg52bOiqVUNyvYXDh//qJ9c79D8sCzMYsoxcJjwqpi7u4ufxQDARTTCaev2I8JqJcDiJCzfTmXS6vMFbnNDyWoyzQIyQ7jYi/KKOVxliE7k8+46/7smodetD03TXTUpXzJ7k8hseAGH/OrCRgSGGE0kAcEvSs/jVMmBK0ZzSpqTRKX4AhlMjEaG4jKjx6gaVfuOUYZxgYe2FQTA8rXNpPH9NEV3+QuGAovMfkBzM41yAKWuEghsHDvg5/wxo6IDna0NJCSGo07ImjrTVAszPg/ny2korL/XJLWJO/yMDDElycuIQ5oCqhyHbjN1JLbTMLXzbbCy0pMAHGX6iHp+vr2bXUkMNkJPLLeOAGjsVmL5oJjnMdpLZ00F8ByLAp+qeG3HiKsYVB4HXGkhgNx9ji0sd4+lAL1yG1w97t1BNSxrQdRMiiulOVYOwA3/oiu8o8cXxVs2NzibHonG/SFZxWjJos981t8J6FItHzo9LKYISYIn0vfi4RjUlDLtlctVHz7HGDe75Efv3gaxAnlMhGFgRGWkV43ryzv3HcVdwJ4j6unrRq45j9wCkcUgFJv6porui0M5l7ONsqgT4jPcsP1DWPj/YawSw7MyBnO+W32m8xgdy6RL2bIY1I8KBEwMOajxXkkmND69w9Of9+9jrigPFA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: kube-system
