---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: cert-manager
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    crds:
      enabled: true
