apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: findingway
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    cert-manager.io/renew-before: "720h"
spec:
  secretName: tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - findingway.io
  - "*.findingway.io"
