apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: findingway
spec:
  secretName: tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - findingway.io
  - "*.findingway.io"
