apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  base: findingway

resources:
- ./namespace.yaml
- ./sealed-secret.yaml
- ./admin.yaml
- ./bot.yaml
- ./notifier.yaml
- ./poster.yaml
- ./pruner.yaml
- ./receiver.yaml
- ./site.yaml
- ./ingress.yaml
- ./seeder.yaml
- ./traefik.yaml
- ./certificate.yaml

images:
- name: ghcr.io/naurffxiv/findingway/bot
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/scraper
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/pruner
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/poster
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/notifier
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/admin
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/receiver
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/site
  newTag: sha-7843eaa
- name: ghcr.io/naurffxiv/findingway/seeder
  newTag: sha-7843eaa

patches:
- target:
    kind: Job
    name: seeder
  patch: |-
    - op: replace
      path: /metadata/name
      value: seeder-7843eaa
