apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  base: findingway

resources:
- ./namespace.yaml
- ./sealed-secret.yaml
- ./bot.yaml
- ./scraper.yaml
- ./pruner.yaml
- ./poster.yaml
- ./notifier.yaml
- ./admin.yaml
- ./receiver.yaml
- ./site.yaml
- ./ingress.yaml
- ./certificate.yaml

images:
- name: ghcr.io/naurffxiv/findingway/bot
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/scraper
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/pruner
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/poster
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/notifier
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/admin
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/receiver
  newTag: sha-cbdf778
- name: ghcr.io/naurffxiv/findingway/site
  newTag: sha-cbdf778
