apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  base: findingway

resources:
- ./namespace.yaml
- ./sealed-secret.yaml
- ./bot.yaml
- ./scraper.yaml
- ./pruner.yaml
- ./poster.yaml
- ./notifier.yaml
- ./admin.yaml

images:
- name: ghcr.io/naurffxiv/findingway/bot
  newTag: sha-e7b4e4b
- name: ghcr.io/naurffxiv/findingway/scraper
  newTag: sha-e7b4e4b
- name: ghcr.io/naurffxiv/findingway/pruner
  newTag: sha-e7b4e4b
- name: ghcr.io/naurffxiv/findingway/poster
  newTag: sha-e7b4e4b
- name: ghcr.io/naurffxiv/findingway/notifier
  newTag: sha-e7b4e4b
- name: ghcr.io/naurffxiv/findingway/admin
  newTag: sha-e7b4e4b
