apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  base: findingway

resources:
- ./namespace.yaml
- ./sealed-secret.yaml
- ./bot.yaml
- ./scraper.yaml
- ./pruner.yaml
- ./poster.yaml
- ./notifier.yaml
images:
- name: ghcr.io/naurffxiv/findingway/bot
  newTag: sha-a3fcb70
- name: ghcr.io/naurffxiv/findingway/scraper
  newTag: sha-a3fcb70
- name: ghcr.io/naurffxiv/findingway/pruner
  newTag: sha-a3fcb70
- name: ghcr.io/naurffxiv/findingway/poster
  newTag: sha-a3fcb70
- name: ghcr.io/naurffxiv/findingway/notifier
  newTag: sha-a3fcb70
