apiVersion: batch/v1
kind: Job
metadata:
  name: seeder
  namespace: findingway
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: findingway
        component: seeder
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: github
      containers:
      - name: seeder
        image: ghcr.io/naurffxiv/findingway/seeder:latest
        ports:
        - containerPort: 8080
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        envFrom:
        - secretRef:
            name: env
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
