---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m0s
  url:  https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: INFO
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: findingway.io
        external-dns.alpha.kubernetes.io/target: findingway.io
        service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
        service.beta.kubernetes.io/vultr-loadbalancer-https-ports: "443"
        service.beta.kubernetes.io/vultr-loadbalancer-ssl: "tls"