---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m0s
  url:  https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: INFO
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep
            names:
              Host: keep
    ingressClass:
      enabled: true
      isDefaultClass: true
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: findingway.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        service.beta.kubernetes.io/vultr-loadbalancer-protocol: "https"
        service.beta.kubernetes.io/vultr-loadbalancer-backend-protocol: "http"
        service.beta.kubernetes.io/vultr-loadbalancer-ssl: "tls"
        service.beta.kubernetes.io/vultr-loadbalancer-ssl-pass-through: "false"
        service.beta.kubernetes.io/vultr-loadbalancer-https-ports: "443"
        service.beta.kubernetes.io/vultr-loadbalancer-ssl-redirect: "true"
        service.beta.kubernetes.io/vultr-loadbalancer-hostname: "findingway.io"
        service.beta.kubernetes.io/vultr-loadbalancer-proxy-protocol: "true"
    ports:
      web:
        asDefault: true
        port: 8000
        exposedPort: 80
        protocol: TCP
      websecure:
        asDefault: true
        port: 8443
        exposedPort: 443
        protocol: TCP