---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m0s
  url:  https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: DEBUG  # Temporarily increase log level for debugging
    ingressClass:
      enabled: true
      isDefaultClass: true
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: findingway.io
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"
      ports:
        websecure:
          port: 443
          expose: true
          exposedPort: 443
          protocol: TCP
        web:
          port: 80
          expose: true
          exposedPort: 80
          protocol: TCP