---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m0s
  url:  https://traefik.github.io/traefik-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
        protocol: TCP
        containerPort: 8000
      websecure:
        port: 443
        expose: true
        exposedPort: 443
        protocol: TCP
        containerPort: 8443
    securityContext:
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      general:
        level: INFO
